package com.beans;

// Generated Nov 24, 2015 2:08:31 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ExamQuestions generated by hbm2java
 */
public class ExamQuestions implements java.io.Serializable
{

    private Integer questionId;
    private Technologies technologies;
    private String question;
    private Set<ExamAnswerChoice> examAnswerChoices = new HashSet<ExamAnswerChoice>(0);

    public Integer getQuestionId()
    {
        return this.questionId;
    }

    public void setQuestionId(Integer questionId)
    {
        this.questionId = questionId;
    }

    public Technologies getTechnologies()
    {
        return this.technologies;
    }

    public void setTechnologies(Technologies technologies)
    {
        this.technologies = technologies;
    }

    public String getQuestion()
    {
        return this.question;
    }

    public void setQuestion(String question)
    {
        this.question = question;
    }

    public Set<ExamAnswerChoice> getExamAnswerChoices()
    {
        return this.examAnswerChoices;
    }

    public void setExamAnswerChoices(Set<ExamAnswerChoice> examAnswerChoices)
    {
        this.examAnswerChoices = examAnswerChoices;
    }

}
