package com.beans;

// Generated Nov 24, 2015 2:08:31 PM by Hibernate Tools 4.0.0

/**
 * ExamAnswerChoice generated by hbm2java
 */
public class ExamAnswerChoice implements java.io.Serializable
{

    private Integer choiceId;
    private ExamQuestions examQuestions;
    private String answerChoice;


    public Integer getChoiceId()
    {
        return this.choiceId;
    }

    public void setChoiceId(Integer choiceId)
    {
        this.choiceId = choiceId;
    }

    public ExamQuestions getExamQuestions()
    {
        return this.examQuestions;
    }

    public void setExamQuestions(ExamQuestions examQuestions)
    {
        this.examQuestions = examQuestions;
    }

    public String getAnswerChoice()
    {
        return this.answerChoice;
    }

    public void setAnswerChoice(String answerChoice)
    {
        this.answerChoice = answerChoice;
    }

}
