package com.beans;

// Generated Nov 24, 2015 2:08:31 PM by Hibernate Tools 4.0.0

/**
 * ExamAnswer generated by hbm2java
 */
public class ExamAnswer implements java.io.Serializable
{

    private Integer answerId;
    private int questionId;
    private int choiceId;

    public Integer getAnswerId()
    {
        return this.answerId;
    }

    public void setAnswerId(Integer answerId)
    {
        this.answerId = answerId;
    }

    public int getQuestionId()
    {
        return this.questionId;
    }

    public void setQuestionId(int questionId)
    {
        this.questionId = questionId;
    }

    public int getChoiceId()
    {
        return this.choiceId;
    }

    public void setChoiceId(int choiceId)
    {
        this.choiceId = choiceId;
    }

}
