package com.beans;

// Generated Nov 24, 2015 2:08:31 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Technologies generated by hbm2java
 */
public class Technologies implements java.io.Serializable
{

    private Integer technologyId;
    private String technologyName;
    private Set<ExamQuestions> examQuestionses = new HashSet<ExamQuestions>(0);


    public Integer getTechnologyId()
    {
        return this.technologyId;
    }

    public void setTechnologyId(Integer technologyId)
    {
        this.technologyId = technologyId;
    }

    public String getTechnologyName()
    {
        return this.technologyName;
    }

    public void setTechnologyName(String technologyName)
    {
        this.technologyName = technologyName;
    }

    public Set<ExamQuestions> getExamQuestionses()
    {
        return this.examQuestionses;
    }

    public void setExamQuestionses(Set<ExamQuestions> examQuestionses)
    {
        this.examQuestionses = examQuestionses;
    }

}
